// Generated by Wrangler by running `wrangler types`

interface Env {
	BASE_URL: "https://cdn.artlu.workers.dev";
	MY_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").MyDurableObject>;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
}
